### PR TITLE
Some fixes to the code

### PR DESCRIPTION
**Pull request by rpeshkov**
See details here:

rpeshkov#1
rpeshkov#2
rpeshkov#3

### CODE REVIEW

**Comment by pekiZG** [comment]
Also want this merge, figured out that download theme is not working.
@akmittal can you please review and make a merge?

**Comment by rpeshkov** [comment]
I guess the project is dead... :(

**Review by akmittal — CHANGES_REQUESTED** [review]
Thanks for pull request, sorry fo not reviewing for so long.

I see there are so many changes in pull request which are cosmetic changes(coding style) which are basically different for different users. And I just don't want to include a dependency for doing just one http request. Please provide the minimal change to fix the issue if you want.

**Comment by rpeshkov** [comment]
@akmittal well, I agree that some changes are cosmetic. But as for request package, I don't see any advantages if I get rid of 'request' package. Yes, it's additional dependency, but it reduces amount of code you need to write. Without it, you would end up adding 2 packages depending on whether you want http or https request. Also, I don't see too much problem with the package since it's devDependency.

**Comment by ttys3** [comment]
@rpeshkov  I've forked this repo and submitted a new plugin:

https://github.com/ttys3/hugofy-vscode

get it via https://marketplace.visualstudio.com/items?itemName=ttys3.hugofy

```bash
ext install ttys3.hugofy
```

**Pull request closed without merging**
